MIME_TYPES = {

    "video/3gpp": ".3gp",
  "application/x-7z-compressed": ".7z",
  "application/atom+xml": ".atom",
  "application/octet-stream": ".bin",
  "image/bmp": ".bmp",
  "application/java-vm": ".class",
  "text/csv": ".csv",
  "text/css": ".css",
  "application/msword": ".doc",
  "application/xml-dtd": ".dtd",
  "application/vnd.ms-fontobject": ".eot",
  "application/x-msdownload": ".exe",
  "video/x-flv": ".flv",
  "image/gif": ".gif",
  "text/html": ".html",
  "image/x-icon": ".ico",
  "text/calendar": ".ics",
  "text/x-java-source, text/java": ".java",
  "image/jpeg": ".jpeg",
  "application/json": ".json",
  "application/ld+json": ".jsonld",
  "application/javascript": ".js",
  "application/vnd.google-earth.kml+xml": ".kml",
  "application/vnd.google-earth.kmz": ".kmz",
  "video/quicktime": ".mov",
  "audio/mpeg": ".mp3",
  "video/mp4": ".mp4",
  "audio/mp4": ".m4a",
  "video/mpeg": ".mpeg",
  "application/vnd.oasis.opendocument.presentation": ".odp",
  "application/vnd.oasis.opendocument.spreadsheet": ".ods",
  "application/vnd.oasis.opendocument.text": ".odt",
  "audio/ogg, video/ogg": ".ogg",
  "application/pdf": ".pdf",
  "application/x-php": ".php",
  "image/png": ".png",
  "application/postscript": ".ps",
  "application/vnd.ms-powerpoint": ".ppt",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx",
  "application/rdf+xml": ".rdf",
  "application/rss+xml": ".rss",
  "application/rtf": ".rtf",
  "application/x-sh": ".sh",
  "application/soap+xml": ".soap",
  "application/x-sql": ".sql",
  "image/svg+xml": ".svg",
  "application/x-tar": ".tar",
  "image/tiff": ".tiff",
  "application/x-font-ttf": ".ttf",
  "text/plain": ".txt",
  "application/x-www-form-urlencoded": ".url",
  "text/vcard": ".vcf",
  "audio/vnd.wav": ".wav",
  "video/webm": ".webm",
  "image/webp": ".webp",
  "application/font-woff": ".woff",
  "application/font-woff2": ".woff2",
  "application/xhtml+xml": ".xhtml",
  "application/xml, text/xml": ".xml",
  "application/xslt+xml": ".xsl",
  "application/x-xpinstall": ".xpi",
  "application/zip": ".zip",
  "application/x-x509-ca-cert": ".crt",
  "application/vnd.android.package-archive": ".apk",
  "audio/x-aiff": ".aiff",
  "application/x-bzip": ".bz",
  "application/x-bzip2": ".bz2",
  "text/x-c": ".c",
  "application/vnd.ms-cab-compressed": ".cab",
  "application/x-chrome-extension": ".crx",
  "text/x-c++": ".cpp",
  "application/x-deb": ".deb",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
  "application/vnd.ms-excel": ".xls",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
  "application/x-font-otf": ".otf",
  "text/x-pascal": ".pas",
  "application/vnd.ms-powerpoint.presentation.macroEnabled.12": ".pptm",
  "application/vnd.openxmlformats-officedocument.presentationml.slideshow": ".ppsx",
  "application/x-rar-compressed": ".rar",
  "application/x-redhat-package-manager": ".rpm",
  "text/x-sass": ".sass",
  "text/x-scss": ".scss",
  "text/x-shellscript": ".sh",
  "image/tiff-fx": ".tfx",
  "text/x-typescript": ".ts",
  "audio/x-wavpack": ".wv",
  "video/x-ms-wmv": ".wmv",
  "application/xrds+xml": ".xrds",
  "application/zip-compressed": ".zip",
  "application/vnd.android.package-archive": ".apk",
  "application/x-zip-compressed": ".zip"

}

module.exports = MIME_TYPES